application: tbocsincloud
version: 1
runtime: go
api_version: 3

inbound_services:
  - channel_presence

handlers: 
  - url: /(.*\.(js|png|jpg))
    static_files: \1 
    upload: (.*\.(js|png|jpg))

  - url: /.*
    script: _go_app
